cache: 
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

script:
  - docker build . -t jeff-busybox:latest
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - ls $HOME/google-cloud-sdk/bin
  - which gcloud
