#cache:
#  directories:
#  - "$HOME/google-cloud-sdk/"
services:
- docker
script:
- docker build . -t jeff-busybox
before_deploy:
- echo $super_secret_stuff | base64 -d | zcat > client-secret.json
- gcloud auth activate-service-account --key-file client-secret.json
- export BRANCH_NAME="$(echo $TRAVIS_BRANCH | sed 's/[^-A-Za-z0-9]/_/g')"
- export GIT_TAG="$(git describe --tags)"
- export TAGS="latest $TRAVIS_BRANCH $GIT_TAG"
- for tag in $TAGS; do
    echo $tag;
    docker tag jeff-busybox gcr.io/milesm-testbed/jeff-busybox:$tag;
    docker push jeff-busybox gcr.io/milesm-testbed/jeff-busybox:$tag;
  done
deploy:
  skip_cleanup: true
  provider: script
  script: echo "deploy happened in before_deploy"
  on:
    branch: master
