#cache:
#  directories:
#  - "$HOME/google-cloud-sdk/"
services:
- docker
script:
- docker build . -t jeff-busybox
before_deploy:
- openssl aes-256-cbc -K $encrypted_115b5340ff69_key -iv $encrypted_115b5340ff69_iv
  -in client-secret.json.gz.enc -out client-secret.json.gz -d
- gunzip client-secret.json.gz
- gcloud auth activate-service-account --key-file client-secret.json
- export TAGS="latest 123"
- for tag in $TAGS; do
    docker tag jeff-busybox gcr.io/milesm-testbed/jeff-busybox:$tag;
  done
deploy:
  skip_cleanup: true
  provider: script
  script: for tag in $TAGS; do gcloud docker -- push gcr.io/milesm-testbed/jeff-busybox:$tag; done
  on:
    branch: master
