language: python

install:
  - curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-225.0.0-linux-x86_64.tar.gz | tar xzf -
  - source google-cloud-sdk/path.bash.inc
  - echo $GCR_ADMIN_TOKEN | base64 -d > client-secret.json
  - gcloud auth activate-service-account --key-file client-secret.json
  - gcloud auth configure-docker --quiet

env:
  - DOCKER_ROOT=gcr.io/uwit-mci-iam/

before_script:
  - docker-compose version
  - docker version
script:
  - for image in jeff-busybox-a jeff-busybox-b; do
      docker pull ${DOCKER_ROOT}${image} || true ;
      docker tag ${DOCKER_ROOT}${image} ${image} || true;
      docker-compose build;
    done
  - docker run jeff-busybox-b
  - docker run jeff-busybox-a
  - for image in jeff-busybox-a jeff-busybox-b; do
      docker tag ${image} ${DOCKER_ROOT}${image} ;
      docker push ${DOCKER_ROOT}${image} ;
    done
