language: python
install: true
env:
  - DOCKER_ROOT=gcr.io/uwit-mci-iam/
before_script:
  - echo $identityuw-gcr-sa-admin | base64 -d > client-secret.json
  - cat client-secret.json | docker login -u _json_key --password-stdin https://gcr.io
  - docker-compose version
  - docker version
script:
  - for image in jeff-busybox-a jeff-busybox-b; do
      docker pull ${DOCKER_ROOT}${image} || true ;
      docker tag ${DOCKER_ROOT}${image} ${image} || true;
      docker-compose build;
    done
  - docker run jeff-busybox-b
  - docker run jeff-busybox-a
  - for image in jeff-busybox-a jeff-busybox-b; do
      docker tag ${image} ${DOCKER_ROOT}${image} ;
      docker push ${DOCKER_ROOT}${image} ;
    done
