language: python

install:
  - echo $GCR_ADMIN_TOKEN | base64 -d | docker login -u _json_key --password-stdin https://gcr.io

env:
  - DOCKER_ROOT=gcr.io/uwit-mci-iam/

before_script:
  - docker-compose version
  - docker version
script:
  - for image in jeff-busybox-a jeff-busybox-b; do
      docker pull ${DOCKER_ROOT}${image} || true ;
      docker tag ${DOCKER_ROOT}${image} ${image} || true;
      docker-compose build;
    done
  - docker run jeff-busybox-b
  - docker run jeff-busybox-a
  - for image in jeff-busybox-a jeff-busybox-b; do
      docker tag ${image} ${DOCKER_ROOT}${image} ;
      docker push ${DOCKER_ROOT}${image} ;
    done
