cache:
  directories:
  - "$HOME/google-cloud-sdk/"
services:
- docker
script:
- docker build . -t jeff-busybox
before_deploy:
- curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-222.0.0-linux-x86_64.tar.gz | tar xzf - 
- google-cloud-sdk/install.sh
  
- if [ ! -d ${HOME}/google-cloud-sdk ]; 
    then curl https://sdk.cloud.google.com | bash;
  fi
- gcloud --version
- gcloud components update
- openssl aes-256-cbc -K $encrypted_115b5340ff69_key -iv $encrypted_115b5340ff69_iv
  -in client-secret.json.gz.enc -out client-secret.json.gz -d
- gunzip client-secret.json.gz
# - gcloud config set project
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud auth configure-docker
- docker tag jeff-busybox gcr.io/milesm-testbed/jeff-busybox:latest
deploy:
  skip_cleanup: true
  provider: script
  script: docker push gcr.io/milesm-testbed/jeff-busybox:latest
  on:
    branch: master
