version: '3.2'
services:
  jeff-busybox-a:
    build: 
      context: .
      cache_from:
        - gcr.io/milesm-testbed/jeff-busybox-a
    image: gcr.io/milesm-testbed/jeff-busybox-a
  jeff-busybox-b:
    build:
      context: .
      dockerfile: Dockerfile-b
      cache_from:
        - gcr.io/milesm-testbed/jeff-busybox-b
    depends_on:
      - gcr.io/milesm-testbed/jeff-busybox-a
    image: gcr.io/milesm-testbed/jeff-busybox-b
