version: '3'
services:
  busybox-a:
    build: .
    image: gcr.io/milesm-testbed/jeff-busybox-a
  busybox-b:
    build:
      context: .
      dockerfile: Dockerfile-b
    image: gcr.io/milesm-testbed/jeff-busybox-b
