version: '3.2'
services:
  busybox-a:
    build: 
      context: .
      cache_from:
        - gcr.io/milesm-testbed/jeff-busybox-a
    image: gcr.io/milesm-testbed/jeff-busybox-a
  busybox-b:
    build:
      context: .
      dockerfile: Dockerfile-b
      cache_from: 
        - gcr.io/milesm-testbed/jeff-busybox-b
    image: gcr.io/milesm-testbed/jeff-busybox-b
